#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.bin/ctags/Makefile 201784 2010-01-08 11:16:58Z dwmalone $

DEBUG_FLAGS=-g
PROG=	atags
SRCS=	C.c atags.c fortran.c lisp.c print.c tree.c yacc.c
CFLAGS+=-I${.CURDIR}

.include <bsd.prog.mk>
